using System.Collections.Generic;
using ExcelAddIn.Models.MachineType;
using Newtonsoft.Json;

namespace ExcelAddIn.Models.MachineDetails
{
    public class MachineDetailsResponse
    {
        [JsonProperty("capturetime")]
        public string Capturetime { get; set; }

        [JsonProperty("capturetime_epoch")]
        public long CapturetimeEpoch { get; set; }

        [JsonProperty("updatetime")]
        public string Updatetime { get; set; }

        [JsonProperty("localtz")]
        public string Localtz { get; set; }

        [JsonProperty("updatelocation")]
        public string Updatelocation { get; set; }

        [JsonProperty("version")]
        public int Version { get; set; }

        [JsonProperty("tombstone")]
        public bool Tombstone { get; set; }

        [JsonProperty("tombstone_epoch")]
        public int TombstoneEpoch { get; set; }

        [JsonProperty("hash")]
        public string Hash { get; set; }

        [JsonProperty("tag")]
        public string Tag { get; set; }

        [JsonProperty("auto_generated_parent")]
        public object AutoGeneratedParent { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("factory_partner")]
        public string FactoryPartner { get; set; }

        [JsonProperty("factory_location")]
        public string FactoryLocation { get; set; }

        [JsonProperty("recipes")]
        public Recipes Recipes { get; set; }

        [JsonProperty("shift_ids")]
        public List<object> ShiftIds { get; set; }

        [JsonProperty("source_clean")]
        public string SourceClean { get; set; }

        [JsonProperty("source_type")]
        public string SourceType { get; set; }

        [JsonProperty("dcn")]
        public string Dcn { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("etlsettings")]
        public Etlsettings Etlsettings { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }
}